CanariWeb/Models/ApiRequest.cs
using Microsoft.AspNetCore.Mvc;
using static Canaria_Utility.SD;

namespace CanariWeb.Models
{
    public class ApiRequest
    {
        public ApiType ApiType { get; set; } = ApiType.GET;
        public string Url { get; set; }
        public object Data { get; set; }
    }
}

CanariWeb/Models/ApiResponse.cs
using System.Net;

namespace CanariaWeb.Models
{
    public class ApiResponse
    {
        public HttpStatusCode StatusCode { get; set; }
        public bool IsSuccess { get; set; } = true;
        public List<string> ErrorMessages { get; set; }
        public object Result { get; set; }
    }
}

CanariWeb/Models/DTO/ApartmentCreateDto.cs
using System.ComponentModel.DataAnnotations;

namespace CanariaWeb.Models.DTO
{
    public class ApartmentCreateDto
    {
        [Required]
        [MaxLength(30)]
        public string Name { get; set; }
        public string? Details { get; set; }
        [Required]
        public double Rate { get; set; }
        public int Kvm { get; set; }
        public int Occupancy { get; set; }
        public string? ImageUrl { get; set; }
        public string? Comfort { get; set; }
    }
}

CanariWeb/Models/DTO/ApartmentDto.cs
using System.ComponentModel.DataAnnotations;

namespace CanariaWeb.Models.DTO
{
    public class ApartmentDto
    {
        public int ApartmentId { get; set; }
        [Required]
        [MaxLength(30)]
        public string Name { get; set; }
        public string Details { get; set; }
        [Required]
        public double Rate { get; set; }
        public int Kvm { get; set; }
        public int Occupancy { get; set; }
        public string ImageUrl { get; set; }
        public string Comfort { get; set; }
    }
}

CanariWeb/Models/DTO/ApartmentNumberCreateDto.cs
using System.ComponentModel.DataAnnotations;

namespace CanariaWeb.Models.DTO
{
    public class ApartmentNumberCreateDto
    {
        [Required]
        public int ApartmentNo { get; set; }
        [Required]
        public int FkApartmentId { get; set; }
        public string SpecialDetails { get; set; }
    }
}

CanariWeb/Models/DTO/ApartmentNumberDto.cs
using System.ComponentModel.DataAnnotations;

namespace CanariaWeb.Models.DTO
{
    public class ApartmentNumberDto
    {
        [Required]
        public int ApartmentNo { get; set; }
        [Required]
        public int FkApartmentId { get; set; }
        public string SpecialDetails { get; set; }
    }
}

CanariWeb/Models/DTO/ApartmentNumberUpdateDto.cs
using System.ComponentModel.DataAnnotations;

namespace CanariaWeb.Models.DTO
{
    public class ApartmentNumberUpdateDto
    {
        [Required]
        public int ApartmentNo { get; set; }
        [Required]
        public int FkApartmentId { get; set; }
        public string SpecialDetails { get; set; }
    }
}

CanariWeb/Models/DTO/ApartmentUpdateDto.cs
using System.ComponentModel.DataAnnotations;

namespace CanariaWeb.Models.DTO
{
    public class ApartmentUpdateDto
    {
        [Required]
        public int ApartmentId { get; set; }
        [Required]
        [MaxLength(30)]
        public string Name { get; set; }
        public string Details { get; set; }
        [Required]
        public double Rate { get; set; }
        [Required]
        public int Kvm { get; set; }
        [Required]
        public int Occupancy { get; set; }
        [Required]
        public string ImageUrl { get; set; }
        public string Comfort { get; set; }
    }
}

CanariWeb/Models/ErrorViewModel.cs
namespace CanariWeb.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

CanariWeb/Controllers/ApartmentController.cs
using AutoMapper;
using CanariaWeb.Models.DTO;
using CanariWeb.Services.IServices;
using Canaria_Utility;
using CanariaWeb.Models;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.Reflection;
namespace MagicVilla_Web.Controllers
{
	public class ApartmentController : Controller
	{
		private readonly IApartmentService _apartmentService;
		private readonly IMapper _mapper;
		public ApartmentController(IApartmentService apartmentService, IMapper mapper)
		{
			_apartmentService = apartmentService;
			_mapper = mapper;
		}
		public async Task<IActionResult> IndexApartment()
		{
			List<ApartmentDto> list = new();

			var response = await _apartmentService.GetAllAsync<ApiResponse>();
			if (response != null && response.IsSuccess)
			{
				list = JsonConvert.DeserializeObject<List<ApartmentDto>>(Convert.ToString(response.Result));
			}
			return View(list);
		}
		//GET
		public async Task<IActionResult> CreateApartment()
		{
			return View();
		}
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> CreateApartment(ApartmentCreateDto model)
		{
			if (ModelState.IsValid)
			{
				var response = await _apartmentService.CreateAsync<ApiResponse>(model);
				if (response != null && response.IsSuccess)

					return RedirectToAction(nameof(IndexApartment));
			}
			return View(model);
		}

        //GET
        public async Task<IActionResult> UpdateApartment(int apartmentid)
        {
            var response = await _apartmentService.GetAsync<ApiResponse>(apartmentid);
            if (response != null && response.IsSuccess)
			{
				ApartmentDto model = JsonConvert.DeserializeObject<ApartmentDto>(Convert.ToString(response.Result));
				return View(_mapper.Map<ApartmentUpdateDto>(model));
            }  
            return NotFound();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UpdateApartment(ApartmentUpdateDto model)
        {
            if (ModelState.IsValid)
            {
                var response = await _apartmentService.UpdateAsync<ApiResponse>(model);
                if (response != null && response.IsSuccess)
				{
                    return RedirectToAction(nameof(IndexApartment));
                }    
            }
            return View(model);
        }

        public async Task<IActionResult> DeleteApartment(int apartmentId)
		{
			var response = await _apartmentService.GetAsync<ApiResponse>(apartmentId);
			if (response != null && response.IsSuccess)
			{
				ApartmentDto model = JsonConvert.DeserializeObject<ApartmentDto>(Convert.ToString(response.Result));
				return View(model);
			}
			return NotFound();
		}
	}
}

CanariWeb/Controllers/HomeController.cs
using CanariWeb.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace CanariWeb.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

CanariWeb/Views/Apartment/CreateApartment.cshtml
@model CanariaWeb.Models.DTO.ApartmentCreateDto
<form asp-action="CreateApartment">
    <br />
    <div class="container border p-3">
        <h1 class="text-primary">Create Apartment</h1>
        <hr />

        <div class="row">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="col-2">
                <label asp-for="Name" class="control-label pt-2" style="font-size:20px;"></label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>

            <div class="col-2">
                <label asp-for="Rate" class="control-label pt-2" style="font-size:20px;"></label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="Rate" class="form-control" />
                <span asp-validation-for="Rate" class="text-danger"></span>
            </div>

            <div class="col-2">
                <label asp-for="Details" class="control-label pt-2" style="font-size:20px;"></label>
            </div>
            <div class="col-10 pb-3">
                <textarea asp-for="Details" class="form-control" rows="5"></textarea>
                <span asp-validation-for="Details" class="text-danger"></span>
            </div>

            <div class="col-2">
                <label asp-for="ImageUrl" class="control-label pt-2" style="font-size:20px;"></label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="ImageUrl" class="form-control" />
                <span asp-validation-for="ImageUrl" class="text-danger"></span>
            </div>

            <div class="col-2">
                <label asp-for="Occupancy" class="control-label pt-2" style="font-size:20px;"></label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="Occupancy" class="form-control" />
                <span asp-validation-for="Occupancy" class="text-danger"></span>
            </div>

            <div class="col-2">
                <label asp-for="Kvm" class="control-label pt-2" style="font-size:20px;"></label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="Kvm" class="form-control" />
                <span asp-validation-for="Kvm" class="text-danger"></span>
            </div>

            <div class="col-2">
                <label asp-for="Comfort" class="control-label pt-2" style="font-size:20px;"></label>
            </div>
            <div class="col-10 pb-3">
                <textarea asp-for="Comfort" class="form-control"></textarea>
                <span asp-validation-for="Comfort" class="text-danger"></span>
            </div>
            <div class="col-5 offset-2">
                <a asp-action="IndexApartment" asp-controller="Apartment" class="btn-primary btn form-control ">Back to List</a>
            </div>
            <div class="col-5">
                <input type="submit" value="Create" class="btn btn-success form-control" />
            </div>
        </div>
    </div>
</form>


@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

CanariWeb/Views/Apartment/IndexApartment.cshtml
@model IEnumerable<CanariaWeb.Models.DTO.ApartmentDto>
<br />
<div class="container p-4 border">
	<div class="row pb-2">
		<div class="col">
			<h1 class="text-primary">Apartments</h1>
		</div>
		<div class="col text-end pt-1">
			<a asp-controller="Apartment" asp-action="CreateApartment" class="btn btn-outline-primary"><i class="bi bi-plus-square-fill"></i> Create New Apartment</a>
		</div>
	</div>

	<table class="table">
		<thead>
			<tr>
				<th>
					Name
				</th>
				<th>
					Occupany
				</th>
				<th>
					Price
				</th>
				<th></th>
			</tr>
		</thead>
		<tbody>
			@foreach (var item in Model)
			{
				<tr>
					<td>@item.Name</td>
					<td>@item.Occupancy</td>
					<td>@((item.Rate).ToString("c"))</td>
					<td>
						<a asp-controller="Apartment" asp-action="UpdateApartment" asp-route-apartmentId="@item.ApartmentId" class="btn btn-success"><i class="bi bi-pencil-square"></i></a>
						<a asp-controller="Apartment" asp-action="DeleteApartment" asp-route-apartmentId="@item.ApartmentId" class="btn btn-danger"><i class="bi bi-trash-fill"></i></a>
					</td>
				</tr>
			}
		</tbody>
	</table>
</div>

CanariWeb/Views/Apartment/UpdateApartment.cshtml
@model CanariaWeb.Models.DTO.ApartmentUpdateDto

<form asp-action="UpdateApartment">
    <br />
    <div class="container border p-3">
        <h1 class="text-primary">Update Apartment</h1>
        <hr />

        <input hidden asp-for="ApartmentId" />
        <div class="row">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="col-2">
                <label asp-for="Name" class="control-label pt-2" style="font-size:20px;"></label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>

            <div class="col-2">
                <label asp-for="Rate" class="control-label pt-2" style="font-size:20px;"></label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="Rate" class="form-control" />
                <span asp-validation-for="Rate" class="text-danger"></span>
            </div>

            <div class="col-2">
                <label asp-for="Details" class="control-label pt-2" style="font-size:20px;"></label>
            </div>
            <div class="col-10 pb-3">
                <textarea asp-for="Details" class="form-control" rows="5"></textarea>
                <span asp-validation-for="Details" class="text-danger"></span>
            </div>

            <div class="col-2">
                <label asp-for="ImageUrl" class="control-label pt-2" style="font-size:20px;"></label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="ImageUrl" class="form-control" />
                <span asp-validation-for="ImageUrl" class="text-danger"></span>
            </div>

            <div class="col-2">
                <label asp-for="Occupancy" class="control-label pt-2" style="font-size:20px;"></label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="Occupancy" class="form-control" />
                <span asp-validation-for="Occupancy" class="text-danger"></span>
            </div>

            <div class="col-2">
                <label asp-for="Kvm" class="control-label pt-2" style="font-size:20px;"></label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="Kvm" class="form-control" />
                <span asp-validation-for="Kvm" class="text-danger"></span>
            </div>

            <div class="col-2">
                <label asp-for="Comfort" class="control-label pt-2" style="font-size:20px;"></label>
            </div>
            <div class="col-10 pb-3">
                <textarea asp-for="Comfort" class="form-control"></textarea>
                <span asp-validation-for="Comfort" class="text-danger"></span>
            </div>
            <div class="col-5 offset-2">
                <a asp-action="IndexApartment" asp-controller="Apartment" class="btn-primary btn form-control ">Back to List</a>
            </div>
            <div class="col-5">
                <input type="submit" value="Update" class="btn btn-success form-control" />
            </div>
        </div>
    </div>
</form>


@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

CanariWeb/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

CanariWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CanariWeb</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CanariWeb.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.3/font/bootstrap-icons.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CanariWeb</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Apartment" asp-action="IndexApartment">Apartments</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - CanariWeb - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>